/*
Package sounds generates and manipulates sounds.

Overview

Interfaces

Sound:- has constructors for Notes, and modifiers for basic alterations, using time.Duration rather than the abstract units of the signals package. (Sound is a signals.LimitedFunction so can also be manipulated by func's from that package, including being Decoded from a wav file.)

Fundamental Types

Compositor:- an array of signals.Function, potentially Sound's, that is a signals.LimitedFunction itself, generated by adding together its contents, and so is a Sound.

(the duration, limit, for the Compositor, that makes it a signals.LimitedFunction, comes from the contained signals.Function's, so at least one should be a signals.LimitedFunction(Sound))

*/
package sound

