/*
Package sounds generates and manipulates sounds.

Overview

Signals with the x-axis accessed as a time.Duration, and with types to help handle music.

Interfaces

Sound:- a signals.LimitedFunction.

Tone:- neverending Sine wave, a signals.PeriodFunction.

Note:- a Sound with a Period, signals.PeriodicLimitedFunction, set to a whole number of Period's.

(along with basic access with whats in this package, as signals.???Function's, these interfaces can be manipulated by func's from the signals package)

Types

Compositor:- an array of signals.Function, potentially Sound's, that is a signals.LimitedFunction(Sound) itself, and is generated by adding together its contents.

(the end time of a Compositor, that makes it a signals.LimitedFunction, comes from the longest contained signals.Function's, so at least one should be a Sound)

*/
package sound

